// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Energipro - Gerencie suas Contas de Energia",
  description: "Gerencie suas contas de energia, calcule médias e previsões de consumo",
  manifest: "/manifest.json",
  icons: {
    icon: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/8c70773c-0fe5-4c18-a2ab-73052a41a397.jpg",
    apple: "https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/8c70773c-0fe5-4c18-a2ab-73052a41a397.jpg",
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Energipro",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
        <link rel="icon" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/8c70773c-0fe5-4c18-a2ab-73052a41a397.jpg" />
        <link rel="apple-touch-icon" href="https://k6hrqrxuu8obbfwn.public.blob.vercel-storage.com/temp/8c70773c-0fe5-4c18-a2ab-73052a41a397.jpg" />
        <meta name="theme-color" content="#3b82f6" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
